package com.qubaolai.po;

import java.util.Date;

public class Attendance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String employeeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.day
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.time_type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String timeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.start_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.start_type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String startType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.end_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.end_type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String endType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.work_type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String workType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.id
     *
     * @return the value of attendance.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.id
     *
     * @param id the value for attendance.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.employee_number
     *
     * @return the value of attendance.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getEmployeeNumber() {
        return employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.employee_number
     *
     * @param employeeNumber the value for attendance.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEmployeeNumber(String employeeNumber) {
        this.employeeNumber = employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.day
     *
     * @return the value of attendance.day
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.day
     *
     * @param day the value for attendance.day
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.time_type
     *
     * @return the value of attendance.time_type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getTimeType() {
        return timeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.time_type
     *
     * @param timeType the value for attendance.time_type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setTimeType(String timeType) {
        this.timeType = timeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.start_time
     *
     * @return the value of attendance.start_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.start_time
     *
     * @param startTime the value for attendance.start_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.start_type
     *
     * @return the value of attendance.start_type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getStartType() {
        return startType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.start_type
     *
     * @param startType the value for attendance.start_type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setStartType(String startType) {
        this.startType = startType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.end_time
     *
     * @return the value of attendance.end_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.end_time
     *
     * @param endTime the value for attendance.end_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.end_type
     *
     * @return the value of attendance.end_type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getEndType() {
        return endType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.end_type
     *
     * @param endType the value for attendance.end_type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEndType(String endType) {
        this.endType = endType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.work_type
     *
     * @return the value of attendance.work_type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.work_type
     *
     * @param workType the value for attendance.work_type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setWorkType(String workType) {
        this.workType = workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.notes
     *
     * @return the value of attendance.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.notes
     *
     * @param notes the value for attendance.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
}