package com.qubaolai.po;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Integer departmentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.name
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.manager
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String manager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.telephone
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.address
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_number
     *
     * @return the value of department.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Integer getDepartmentNumber() {
        return departmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_number
     *
     * @param departmentNumber the value for department.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setDepartmentNumber(Integer departmentNumber) {
        this.departmentNumber = departmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.manager
     *
     * @return the value of department.manager
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.manager
     *
     * @param manager the value for department.manager
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setManager(String manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.telephone
     *
     * @return the value of department.telephone
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.telephone
     *
     * @param telephone the value for department.telephone
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.address
     *
     * @return the value of department.address
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.address
     *
     * @param address the value for department.address
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.notes
     *
     * @return the value of department.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.notes
     *
     * @param notes the value for department.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
}