package com.qubaolai.po;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String employeeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.gender
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.birthday
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.telephone
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.email
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.address
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.education
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Integer departmentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.position_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Integer positionNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.in_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date inTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.password
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.deviceId
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String deviceid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_number
     *
     * @return the value of employee.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getEmployeeNumber() {
        return employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_number
     *
     * @param employeeNumber the value for employee.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEmployeeNumber(String employeeNumber) {
        this.employeeNumber = employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.gender
     *
     * @return the value of employee.gender
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.gender
     *
     * @param gender the value for employee.gender
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.birthday
     *
     * @return the value of employee.birthday
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.birthday
     *
     * @param birthday the value for employee.birthday
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.telephone
     *
     * @return the value of employee.telephone
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.telephone
     *
     * @param telephone the value for employee.telephone
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.email
     *
     * @return the value of employee.email
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.email
     *
     * @param email the value for employee.email
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.address
     *
     * @return the value of employee.address
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.address
     *
     * @param address the value for employee.address
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.education
     *
     * @return the value of employee.education
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.education
     *
     * @param education the value for employee.education
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.department_number
     *
     * @return the value of employee.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Integer getDepartmentNumber() {
        return departmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.department_number
     *
     * @param departmentNumber the value for employee.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setDepartmentNumber(Integer departmentNumber) {
        this.departmentNumber = departmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.position_number
     *
     * @return the value of employee.position_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Integer getPositionNumber() {
        return positionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.position_number
     *
     * @param positionNumber the value for employee.position_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setPositionNumber(Integer positionNumber) {
        this.positionNumber = positionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.in_time
     *
     * @return the value of employee.in_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.in_time
     *
     * @param inTime the value for employee.in_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.password
     *
     * @return the value of employee.password
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.password
     *
     * @param password the value for employee.password
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.notes
     *
     * @return the value of employee.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.notes
     *
     * @param notes the value for employee.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.deviceId
     *
     * @return the value of employee.deviceId
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.deviceId
     *
     * @param deviceid the value for employee.deviceId
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }
}