package com.qubaolai.po;

import java.util.Date;

public class History {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String employeeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.name
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.gender
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.birthday
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.telephone
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.email
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.address
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.education
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.in_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date inTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.out_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date outTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Integer departmentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.position_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Integer positionNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.status
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.home
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String home;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.id
     *
     * @return the value of history.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.id
     *
     * @param id the value for history.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.employee_number
     *
     * @return the value of history.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getEmployeeNumber() {
        return employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.employee_number
     *
     * @param employeeNumber the value for history.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEmployeeNumber(String employeeNumber) {
        this.employeeNumber = employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.name
     *
     * @return the value of history.name
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.name
     *
     * @param name the value for history.name
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.gender
     *
     * @return the value of history.gender
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.gender
     *
     * @param gender the value for history.gender
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.birthday
     *
     * @return the value of history.birthday
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.birthday
     *
     * @param birthday the value for history.birthday
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.telephone
     *
     * @return the value of history.telephone
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.telephone
     *
     * @param telephone the value for history.telephone
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.email
     *
     * @return the value of history.email
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.email
     *
     * @param email the value for history.email
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.address
     *
     * @return the value of history.address
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.address
     *
     * @param address the value for history.address
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.education
     *
     * @return the value of history.education
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.education
     *
     * @param education the value for history.education
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.in_time
     *
     * @return the value of history.in_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.in_time
     *
     * @param inTime the value for history.in_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.out_time
     *
     * @return the value of history.out_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.out_time
     *
     * @param outTime the value for history.out_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.department_number
     *
     * @return the value of history.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Integer getDepartmentNumber() {
        return departmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.department_number
     *
     * @param departmentNumber the value for history.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setDepartmentNumber(Integer departmentNumber) {
        this.departmentNumber = departmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.position_number
     *
     * @return the value of history.position_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Integer getPositionNumber() {
        return positionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.position_number
     *
     * @param positionNumber the value for history.position_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setPositionNumber(Integer positionNumber) {
        this.positionNumber = positionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.status
     *
     * @return the value of history.status
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.status
     *
     * @param status the value for history.status
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.home
     *
     * @return the value of history.home
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getHome() {
        return home;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.home
     *
     * @param home the value for history.home
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setHome(String home) {
        this.home = home;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.notes
     *
     * @return the value of history.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.notes
     *
     * @param notes the value for history.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
}