package com.qubaolai.po;

import java.util.Date;

public class Lea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lea.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lea.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String employeeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lea.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Integer departmentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lea.start_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lea.end_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lea.reason
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lea.type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lea.manager
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String manager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lea.status
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lea.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lea.id
     *
     * @return the value of lea.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lea.id
     *
     * @param id the value for lea.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lea.employee_number
     *
     * @return the value of lea.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getEmployeeNumber() {
        return employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lea.employee_number
     *
     * @param employeeNumber the value for lea.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEmployeeNumber(String employeeNumber) {
        this.employeeNumber = employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lea.department_number
     *
     * @return the value of lea.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Integer getDepartmentNumber() {
        return departmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lea.department_number
     *
     * @param departmentNumber the value for lea.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setDepartmentNumber(Integer departmentNumber) {
        this.departmentNumber = departmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lea.start_time
     *
     * @return the value of lea.start_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lea.start_time
     *
     * @param startTime the value for lea.start_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lea.end_time
     *
     * @return the value of lea.end_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lea.end_time
     *
     * @param endTime the value for lea.end_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lea.reason
     *
     * @return the value of lea.reason
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lea.reason
     *
     * @param reason the value for lea.reason
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lea.type
     *
     * @return the value of lea.type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lea.type
     *
     * @param type the value for lea.type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lea.manager
     *
     * @return the value of lea.manager
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lea.manager
     *
     * @param manager the value for lea.manager
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setManager(String manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lea.status
     *
     * @return the value of lea.status
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lea.status
     *
     * @param status the value for lea.status
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lea.notes
     *
     * @return the value of lea.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lea.notes
     *
     * @param notes the value for lea.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
}