package com.qubaolai.po;

import java.util.Date;

public class Move {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String employeeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move.before
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Integer before;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move.after
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Integer after;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move.time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move.manager
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String manager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column move.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move.id
     *
     * @return the value of move.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move.id
     *
     * @param id the value for move.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move.employee_number
     *
     * @return the value of move.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getEmployeeNumber() {
        return employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move.employee_number
     *
     * @param employeeNumber the value for move.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEmployeeNumber(String employeeNumber) {
        this.employeeNumber = employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move.before
     *
     * @return the value of move.before
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Integer getBefore() {
        return before;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move.before
     *
     * @param before the value for move.before
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setBefore(Integer before) {
        this.before = before;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move.after
     *
     * @return the value of move.after
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Integer getAfter() {
        return after;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move.after
     *
     * @param after the value for move.after
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setAfter(Integer after) {
        this.after = after;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move.time
     *
     * @return the value of move.time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move.time
     *
     * @param time the value for move.time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move.manager
     *
     * @return the value of move.manager
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move.manager
     *
     * @param manager the value for move.manager
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setManager(String manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column move.notes
     *
     * @return the value of move.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column move.notes
     *
     * @param notes the value for move.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
}