package com.qubaolai.po;

import java.util.Date;

public class Overtime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overtime.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overtime.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Integer departmentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overtime.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String employeeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overtime.day
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overtime.start_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overtime.end_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overtime.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overtime.id
     *
     * @return the value of overtime.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overtime.id
     *
     * @param id the value for overtime.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overtime.department_number
     *
     * @return the value of overtime.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Integer getDepartmentNumber() {
        return departmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overtime.department_number
     *
     * @param departmentNumber the value for overtime.department_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setDepartmentNumber(Integer departmentNumber) {
        this.departmentNumber = departmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overtime.employee_number
     *
     * @return the value of overtime.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getEmployeeNumber() {
        return employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overtime.employee_number
     *
     * @param employeeNumber the value for overtime.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEmployeeNumber(String employeeNumber) {
        this.employeeNumber = employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overtime.day
     *
     * @return the value of overtime.day
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overtime.day
     *
     * @param day the value for overtime.day
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overtime.start_time
     *
     * @return the value of overtime.start_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overtime.start_time
     *
     * @param startTime the value for overtime.start_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overtime.end_time
     *
     * @return the value of overtime.end_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overtime.end_time
     *
     * @param endTime the value for overtime.end_time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overtime.notes
     *
     * @return the value of overtime.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overtime.notes
     *
     * @param notes the value for overtime.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
}