package com.qubaolai.po;

import java.util.Date;

public class RewardsPunishment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rewards_punishment.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rewards_punishment.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String employeeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rewards_punishment.type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rewards_punishment.reason
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rewards_punishment.money
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Float money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rewards_punishment.time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rewards_punishment.manager
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String manager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rewards_punishment.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rewards_punishment.id
     *
     * @return the value of rewards_punishment.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rewards_punishment.id
     *
     * @param id the value for rewards_punishment.id
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rewards_punishment.employee_number
     *
     * @return the value of rewards_punishment.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getEmployeeNumber() {
        return employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rewards_punishment.employee_number
     *
     * @param employeeNumber the value for rewards_punishment.employee_number
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setEmployeeNumber(String employeeNumber) {
        this.employeeNumber = employeeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rewards_punishment.type
     *
     * @return the value of rewards_punishment.type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rewards_punishment.type
     *
     * @param type the value for rewards_punishment.type
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rewards_punishment.reason
     *
     * @return the value of rewards_punishment.reason
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rewards_punishment.reason
     *
     * @param reason the value for rewards_punishment.reason
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rewards_punishment.money
     *
     * @return the value of rewards_punishment.money
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rewards_punishment.money
     *
     * @param money the value for rewards_punishment.money
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rewards_punishment.time
     *
     * @return the value of rewards_punishment.time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rewards_punishment.time
     *
     * @param time the value for rewards_punishment.time
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rewards_punishment.manager
     *
     * @return the value of rewards_punishment.manager
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rewards_punishment.manager
     *
     * @param manager the value for rewards_punishment.manager
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setManager(String manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rewards_punishment.notes
     *
     * @return the value of rewards_punishment.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rewards_punishment.notes
     *
     * @param notes the value for rewards_punishment.notes
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
}