package com.qubaolai.mapper;

import com.qubaolai.po.Attendance;
import com.qubaolai.po.AttendanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttendanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    long countByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int deleteByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int insert(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int insertSelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    List<Attendance> selectByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    Attendance selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") Attendance record, @Param("example") AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByExample(@Param("record") Attendance record, @Param("example") AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByPrimaryKeySelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByPrimaryKey(Attendance record);
}