package com.qubaolai.mapper;

import com.qubaolai.po.Lea;
import com.qubaolai.po.LeaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LeaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lea
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    long countByExample(LeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lea
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int deleteByExample(LeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lea
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lea
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int insert(Lea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lea
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int insertSelective(Lea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lea
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    List<Lea> selectByExample(LeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lea
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    Lea selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lea
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") Lea record, @Param("example") LeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lea
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByExample(@Param("record") Lea record, @Param("example") LeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lea
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByPrimaryKeySelective(Lea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lea
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByPrimaryKey(Lea record);
}