package com.qubaolai.mapper;

import com.qubaolai.po.Move;
import com.qubaolai.po.MoveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MoveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    long countByExample(MoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int deleteByExample(MoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int insert(Move record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int insertSelective(Move record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    List<Move> selectByExample(MoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    Move selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") Move record, @Param("example") MoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByExample(@Param("record") Move record, @Param("example") MoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByPrimaryKeySelective(Move record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table move
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByPrimaryKey(Move record);
}