package com.qubaolai.mapper;

import com.qubaolai.po.Overtime;
import com.qubaolai.po.OvertimeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OvertimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    long countByExample(OvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int deleteByExample(OvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int insert(Overtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int insertSelective(Overtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    List<Overtime> selectByExample(OvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    Overtime selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") Overtime record, @Param("example") OvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByExample(@Param("record") Overtime record, @Param("example") OvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByPrimaryKeySelective(Overtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overtime
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByPrimaryKey(Overtime record);
}