package com.qubaolai.mapper;

import com.qubaolai.po.RewardsPunishment;
import com.qubaolai.po.RewardsPunishmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RewardsPunishmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewards_punishment
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    long countByExample(RewardsPunishmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewards_punishment
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int deleteByExample(RewardsPunishmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewards_punishment
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewards_punishment
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int insert(RewardsPunishment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewards_punishment
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int insertSelective(RewardsPunishment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewards_punishment
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    List<RewardsPunishment> selectByExample(RewardsPunishmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewards_punishment
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    RewardsPunishment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewards_punishment
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") RewardsPunishment record, @Param("example") RewardsPunishmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewards_punishment
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByExample(@Param("record") RewardsPunishment record, @Param("example") RewardsPunishmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewards_punishment
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByPrimaryKeySelective(RewardsPunishment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rewards_punishment
     *
     * @mbg.generated Tue Oct 29 15:10:59 CST 2019
     */
    int updateByPrimaryKey(RewardsPunishment record);
}